### ISSUE TITLE
Remove the link to the Ticket from the Ticket subject

### ISSUE THREAD

**Issue by karrla** [toladata/TolaWork#122]
We'd like to remove the Subject link to the ticket page, so that we remove the ability to get to the old ticket page view.

**Comment by karrla** [comment]
Update.  Since we removed the link to the ticket, we will not have a way to link to a ticket since the "View more Details" does not produce a link for the user.  I created a new ticket to document the need for a new COPY link: #150

**Comment by joash** [comment]
By removing the link to the ticket (or removing the ability to open individual tickets from the list of tickets in TW) from the ticket listing page causes problems with (1) getting the status of individual tickets from github (2) Synching ticket status; closing a ticket in github also closes in TW (3) Checking github labels and so providing progress of such a ticket in TW (4) Generating a ticket URL for a ticket description in github so that users can click from github and access the ticket in TW. All these TW/github enhancements will have to be re-written and I'm just thinking that if there isn't any bug with allowing users to access individual tickets from the ticket listing, we would as well leave that title link in ticket list page.
