### ISSUE TITLE
Create ability to nest knowledge base categories

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#18]
<a href="https://github.com/karrla"><img src="https://avatars.githubusercontent.com/u/15875770?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [karrla](https://github.com/karrla)**
_Wednesday Dec 09, 2015 at 18:47 GMT_
_Originally opened as https://github.com/mercycorps/tola-help/issues/44_

---

We'd like to nest categories in the the knowlege base like:
+Data Collection
- Ona
- ODK

+Tola Activity
- Workflow
- Indicators
- Form Library
- Reports

**Comment by karrla** [comment]
What I think we want is the articles to be in a nested list so that the user just sees the top level category when they go to the KB page and then when they click a category the will see a list of articles in that category. Similar to the FAQ collaspe/expand OR something like this would work http://demo.herothemes.com/knowall/
