### ISSUE TITLE
Click on manage ticket link and error is thrown

### ISSUE THREAD

**Issue by glind** [toladata/TolaWork#185]
http://tola.work/helpdesk/tickets/743/cc/

The manage link should allow a user to assign other users or themselves to be cc'd on ticket changes etc.  When you click on the link an error is thrown.  I have not confirmed this for other tickets just the one above.

**Comment by karrla** [comment]
![uploads/ab4fd209-a7e7-4b52-aecb-d4252a24faa1/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fab4fd209-a7e7-4b52-aecb-d4252a24faa1%2Fblob)

**Comment by karrla** [comment]
The issue is when you try to click add a new e-mail to the list, the user gets the following error: 

VariableDoesNotExist at /helpdesk/tickets/404/cc/add/
Failed lookup for key [helper] in u'\n\n\n\n\n    \n    \n        \n            \n                \n                \n\n<tr>\n    <th><label for="id_user">User:</label></th>\n    <td>\n        \n\n        <select id="id_user" name="user">\n<option value="" selected="selected">---------</option>\n<option value="19">aamaral</option>\n<option value="29">afazel</option>\n<option value="17">afernandes</option>\n<option value="35">ahause</option>\n<option value="34">amachalani</option>\n<option value="31">amanoogian</option>\n<option value="21">amembaj</option>\n<option value="37">amyhause</option>\n<option value="73">anne</option>\n<option value="55">Asharjaby</option>\n<option value="9">atpham</option>\n<option value="28">bwesterman</option>\n<option value="57">Carol</option>\n<option value="12">clivingstone</option>\n<option value="56">clivingstonee3e0a402a0d549c3</option>\n<option value="53">dborchers</option>\n<option value="62">dgillespie</option>\n<option value="69">eintern</option>\n<option value="40">erhes</option>\n<option value="16">esalazar</option>\n<option value="5">esinn</option>\n<option value="38">fabed</option>\n<option value="39">fabed@mercycorps.org</option>\n<option value="61">faith</option>\n<option value="66">faithnekesa.cs</option>\n<option value="64">faynekesa</option>\n<option value="70">gichiraanne</option>\n<option value="11">glind</option>\n<option value="2">gwlind</option>\n<option value="41">Hisham</option>\n<option value="10">jberry</option>\n<option value="15">jcarlson</option>\n<option value="44">jcolvard</option>\n<option value="68">joash</option>\n<option value="22">jscantlan</option>\n<option value="32">jwishnie</option>\n<option value="8">ksandstrom</option>\n<option value="49">kstest</option>\n<option value="50">kstester</option>\n<option value="18">kwakwaya</option>\n<option value="54">ldelgado</option>\n<option value="45">lkeita</option>\n<option value="43">lkeita@mercycorps.org</option>\n<option value="25">mbakke</option>\n<option value="23">mhassani</option>\n<option value="3">mkhan</option>\n<option value="27">mrhynardgeil</option>\n<option value="7">msadat</option>\n<option value="59">mshabo</option>\n<option value="58">mstfait</option>\n<option value="47">mstyslinger</option>\n<option value="6">nadhikari</option>\n<option value="14">nbuzdar</option>\n<option value="13">nnajjar</option>\n<option value="42">nshahed</option>\n<option value="30">nshakya</option>\n<option value="65">odeny.peter</option>\n<option value="63">odenypeter</option>\n<option value="67">odenypeter5410c778bb934af1</option>\n<option value="51">owiticarol</option>\n<option value="52">owiticarol@gmail.com</option>\n<option value="72">peter</option>\n<option value="26">rmomani</option>\n<option value="24">shemingway</option>\n<option value="20">skouzi</option>\n<option value="60">systems</option>\n<option value="33">tcraft</option>\n<option value="36">tola</option>\n<option value="71">tola2</option>\n<option value="48">tshaqalaih</option>\n<option value="46">welmer</option>\n</select>\n        <br /><span class="helptext">User who wishes to receive updates for this ticket.</span>\n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_email">E-Mail Address:</label></th>\n    <td>\n        \n\n        <input id="id_email" maxlength="254" name="email" type="email" />\n        <br /><span class="helptext">For non-user followers, enter their e-mail address</span>\n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_can_view">Can View Ticket?</label></th>\n    <td>\n        \n\n        <input id="id_can_view" name="can_view" type="checkbox" />\n        <br /><span class="helptext">Can this CC login to view the ticket details?</span>\n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_can_update">Can Update Ticket?</label></th>\n    <td>\n        \n\n        <input id="id_can_update" name="can_update" type="checkbox" />\n        <br /><span class="helptext">Can this CC login and update the ticket?</span>\n        \n    </td>\n</tr>\n\n\n            \n        \n        \n    \n\n\n'
Request Method:	GET
Request URL:	http://dev.tola.work/helpdesk/tickets/404/cc/add/
Django Version:	1.8.2
Exception Type:	VariableDoesNotExist
Exception Value:	
Failed lookup for key [helper] in u'\n\n\n\n\n    \n    \n        \n            \n                \n                \n\n<tr>\n    <th><label for="id_user">User:</label></th>\n    <td>\n        \n\n        <select id="id_user" name="user">\n<option value="" selected="selected">---------</option>\n<option value="19">aamaral</option>\n<option value="29">afazel</option>\n<option value="17">afernandes</option>\n<option value="35">ahause</option>\n<option value="34">amachalani</option>\n<option value="31">amanoogian</option>\n<option value="21">amembaj</option>\n<option value="37">amyhause</option>\n<option value="73">anne</option>\n<option value="55">Asharjaby</option>\n<option value="9">atpham</option>\n<option value="28">bwesterman</option>\n<option value="57">Carol</option>\n<option value="12">clivingstone</option>\n<option value="56">clivingstonee3e0a402a0d549c3</option>\n<option value="53">dborchers</option>\n<option value="62">dgillespie</option>\n<option value="69">eintern</option>\n<option value="40">erhes</option>\n<option value="16">esalazar</option>\n<option value="5">esinn</option>\n<option value="38">fabed</option>\n<option value="39">fabed@mercycorps.org</option>\n<option value="61">faith</option>\n<option value="66">faithnekesa.cs</option>\n<option value="64">faynekesa</option>\n<option value="70">gichiraanne</option>\n<option value="11">glind</option>\n<option value="2">gwlind</option>\n<option value="41">Hisham</option>\n<option value="10">jberry</option>\n<option value="15">jcarlson</option>\n<option value="44">jcolvard</option>\n<option value="68">joash</option>\n<option value="22">jscantlan</option>\n<option value="32">jwishnie</option>\n<option value="8">ksandstrom</option>\n<option value="49">kstest</option>\n<option value="50">kstester</option>\n<option value="18">kwakwaya</option>\n<option value="54">ldelgado</option>\n<option value="45">lkeita</option>\n<option value="43">lkeita@mercycorps.org</option>\n<option value="25">mbakke</option>\n<option value="23">mhassani</option>\n<option value="3">mkhan</option>\n<option value="27">mrhynardgeil</option>\n<option value="7">msadat</option>\n<option value="59">mshabo</option>\n<option value="58">mstfait</option>\n<option value="47">mstyslinger</option>\n<option value="6">nadhikari</option>\n<option value="14">nbuzdar</option>\n<option value="13">nnajjar</option>\n<option value="42">nshahed</option>\n<option value="30">nshakya</option>\n<option value="65">odeny.peter</option>\n<option value="63">odenypeter</option>\n<option value="67">odenypeter5410c778bb934af1</option>\n<option value="51">owiticarol</option>\n<option value="52">owiticarol@gmail.com</option>\n<option value="72">peter</option>\n<option value="26">rmomani</option>\n<option value="24">shemingway</option>\n<option value="20">skouzi</option>\n<option value="60">systems</option>\n<option value="33">tcraft</option>\n<option value="36">tola</option>\n<option value="71">tola2</option>\n<option value="48">tshaqalaih</option>\n<option value="46">welmer</option>\n</select>\n        <br /><span class="helptext">User who wishes to receive updates for this ticket.</span>\n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_email">E-Mail Address:</label></th>\n    <td>\n        \n\n        <input id="id_email" maxlength="254" name="email" type="email" />\n        <br /><span class="helptext">For non-user followers, enter their e-mail address</span>\n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_can_view">Can View Ticket?</label></th>\n    <td>\n        \n\n        <input id="id_can_view" name="can_view" type="checkbox" />\n        <br /><span class="helptext">Can this CC login to view the ticket details?</span>\n        \n    </td>\n</tr>\n\n\n            \n                \n                \n\n<tr>\n    <th><label for="id_can_update">Can Update Ticket?</label></th>\n    <td>\n        \n\n        <input id="id_can_update" name="can_update" type="checkbox" />\n        <br /><span class="helptext">Can this CC login and update the ticket?</span>\n        \n    </td>\n</tr>\n\n\n            \n        \n        \n    \n\n\n'
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/template/base.py in _resolve_lookup, line 839
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/home/django/tola-help',
 '/home/django/tola-help/tola-help',
 '/usr/local/bin',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/home/django/tola-help/project',
 '/home/django/tola-help']
Server time:	Sun, 4 Dec 2016 19:49:05 -0800
